package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.ColocadorImagenes;
import minijuegoslectogo.controladores.CtrlVistaMenuPrincipal;

/**
 *
 * @author Baiza
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {
    
    private CtrlVistaMenuPrincipal objCMVP;
    private ColocadorImagenes objCI;
    
    
    public VistaMenuPrincipal() {
        initComponents();
        objCMVP = new CtrlVistaMenuPrincipal(this);
        objCI = new ColocadorImagenes();
        objCI.setImage(fondo, "src/minijuegoslectogo/assets/imagenes/Menus/Menus.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoMenu = new javax.swing.JPanel();
        btnSonidoSalir = new javax.swing.JButton();
        btnSonidoPuntuacion = new javax.swing.JButton();
        btnGuiaLarga = new javax.swing.JButton();
        btnLectoGo = new javax.swing.JButton();
        btnSonidoMinijuegos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPuntuacion = new javax.swing.JButton();
        btnMinijuegos = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSonidoSalir.setBorder(null);
        btnSonidoSalir.setBorderPainted(false);
        btnSonidoSalir.setContentAreaFilled(false);
        btnSonidoSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnSonidoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 40, 50));

        btnSonidoPuntuacion.setBorder(null);
        btnSonidoPuntuacion.setBorderPainted(false);
        btnSonidoPuntuacion.setContentAreaFilled(false);
        btnSonidoPuntuacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSonidoPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoPuntuacionActionPerformed(evt);
            }
        });
        fondoMenu.add(btnSonidoPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 40, 50));

        btnGuiaLarga.setBorder(null);
        btnGuiaLarga.setBorderPainted(false);
        btnGuiaLarga.setContentAreaFilled(false);
        btnGuiaLarga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnGuiaLarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, 50));

        btnLectoGo.setBorder(null);
        btnLectoGo.setBorderPainted(false);
        btnLectoGo.setContentAreaFilled(false);
        btnLectoGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnLectoGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 50, 50));

        btnSonidoMinijuegos.setBorder(null);
        btnSonidoMinijuegos.setBorderPainted(false);
        btnSonidoMinijuegos.setContentAreaFilled(false);
        btnSonidoMinijuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnSonidoMinijuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 40, 50));

        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 180, 80));

        btnPuntuacion.setBorder(null);
        btnPuntuacion.setBorderPainted(false);
        btnPuntuacion.setContentAreaFilled(false);
        btnPuntuacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 260, 80));

        btnMinijuegos.setBorder(null);
        btnMinijuegos.setBorderPainted(false);
        btnMinijuegos.setContentAreaFilled(false);
        btnMinijuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnMinijuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 260, 80));
        fondoMenu.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSonidoPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSonidoPuntuacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuiaLarga;
    public javax.swing.JButton btnLectoGo;
    public javax.swing.JButton btnMinijuegos;
    public javax.swing.JButton btnPuntuacion;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSonidoMinijuegos;
    public javax.swing.JButton btnSonidoPuntuacion;
    public javax.swing.JButton btnSonidoSalir;
    private javax.swing.JLabel fondo;
    public javax.swing.JPanel fondoMenu;
    // End of variables declaration//GEN-END:variables
}
