package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.ColocadorImagenes;
import minijuegoslectogo.controladores.CtrlVistaMenuMinijuegos;
/**
 *
 * @author Baiza
 */
public class VistaMenuMinijuegos extends javax.swing.JFrame {
    
    private CtrlVistaMenuMinijuegos objCMVP;
    private ColocadorImagenes objCI;
    
    
    public VistaMenuMinijuegos() {
        initComponents();
        objCMVP = new CtrlVistaMenuMinijuegos(this);
        objCI = new ColocadorImagenes();
        objCI.setImage(fondo, "src/minijuegoslectogo/assets/imagenes/Menus/MenuMinijuegos.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoMenu = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnAbecedario = new javax.swing.JButton();
        btnVocales = new javax.swing.JButton();
        btnArrLasPal = new javax.swing.JButton();
        btnMeliza = new javax.swing.JButton();
        btnMelissa = new javax.swing.JButton();
        btnAhorcado = new javax.swing.JButton();
        btnImagenesYPalabras = new javax.swing.JButton();
        btnCompletaLasOraciones = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 180, 80));

        btnAbecedario.setBorder(null);
        btnAbecedario.setBorderPainted(false);
        btnAbecedario.setContentAreaFilled(false);
        btnAbecedario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnAbecedario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, 70));

        btnVocales.setBorder(null);
        btnVocales.setBorderPainted(false);
        btnVocales.setContentAreaFilled(false);
        btnVocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnVocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 190, 70));

        btnArrLasPal.setBorder(null);
        btnArrLasPal.setBorderPainted(false);
        btnArrLasPal.setContentAreaFilled(false);
        btnArrLasPal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnArrLasPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 70));

        btnMeliza.setBorder(null);
        btnMeliza.setBorderPainted(false);
        btnMeliza.setContentAreaFilled(false);
        btnMeliza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnMeliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 190, 70));

        btnMelissa.setBorder(null);
        btnMelissa.setBorderPainted(false);
        btnMelissa.setContentAreaFilled(false);
        btnMelissa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnMelissa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 190, 70));

        btnAhorcado.setBorder(null);
        btnAhorcado.setBorderPainted(false);
        btnAhorcado.setContentAreaFilled(false);
        btnAhorcado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnAhorcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 70));

        btnImagenesYPalabras.setBorder(null);
        btnImagenesYPalabras.setBorderPainted(false);
        btnImagenesYPalabras.setContentAreaFilled(false);
        btnImagenesYPalabras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnImagenesYPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 190, 70));

        btnCompletaLasOraciones.setBorder(null);
        btnCompletaLasOraciones.setBorderPainted(false);
        btnCompletaLasOraciones.setContentAreaFilled(false);
        btnCompletaLasOraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoMenu.add(btnCompletaLasOraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 190, 70));
        fondoMenu.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuMinijuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbecedario;
    public javax.swing.JButton btnAhorcado;
    public javax.swing.JButton btnArrLasPal;
    public javax.swing.JButton btnCompletaLasOraciones;
    public javax.swing.JButton btnImagenesYPalabras;
    public javax.swing.JButton btnMelissa;
    public javax.swing.JButton btnMeliza;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVocales;
    private javax.swing.JLabel fondo;
    public javax.swing.JPanel fondoMenu;
    // End of variables declaration//GEN-END:variables
}
