/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.CtrlVistaImagenesYPalabras;

/**
 *
 * @author Baiza
 */
public class VistaMiniImagenesYPalabras extends javax.swing.JFrame {

   
    private CtrlVistaImagenesYPalabras objIYP;
    
    public VistaMiniImagenesYPalabras() {
        initComponents();
        objIYP = new CtrlVistaImagenesYPalabras(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Imagenes = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnRepetirSonido = new javax.swing.JButton();
        labelPuntuacion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnOpcionB = new javax.swing.JButton();
        btnOpcionA = new javax.swing.JButton();
        btnOpcionD = new javax.swing.JButton();
        btnOpcionC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagenes.setBackground(new java.awt.Color(255, 102, 0));
        Imagenes.setForeground(new java.awt.Color(204, 0, 204));
        Imagenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Imagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 270, 270));

        btnSalir.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        btnSalir.setText("Salir");
        jPanel4.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 170, 60));

        btnIniciar.setText("Iniciar");
        jPanel4.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 170, 60));

        btnRepetirSonido.setText("jButton2");
        jPanel4.add(btnRepetirSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 60));

        labelPuntuacion.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        labelPuntuacion.setForeground(new java.awt.Color(255, 0, 0));
        labelPuntuacion.setText("Hola");
        jPanel4.add(labelPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 90, 70));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcionB.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        btnOpcionB.setToolTipText("");
        jPanel5.add(btnOpcionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 320, 60));

        btnOpcionA.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jPanel5.add(btnOpcionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 60));

        btnOpcionD.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jPanel5.add(btnOpcionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 320, 60));

        btnOpcionC.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jPanel5.add(btnOpcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 60));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 700, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMiniImagenesYPalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Imagenes;
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnOpcionA;
    public javax.swing.JButton btnOpcionB;
    public javax.swing.JButton btnOpcionC;
    public javax.swing.JButton btnOpcionD;
    public javax.swing.JButton btnRepetirSonido;
    public javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel labelPuntuacion;
    // End of variables declaration//GEN-END:variables
}
