/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.CtrlVistaMenuPrincipal;

/**
 *
 * @author Baiza
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    private CtrlVistaMenuPrincipal objMenu;
    public VistaMenuPrincipal() {
        initComponents();
        objMenu = new  CtrlVistaMenuPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSonidoSalir = new javax.swing.JButton();
        btnSonidoPuntuacion = new javax.swing.JButton();
        btnGuiaLarga = new javax.swing.JButton();
        btnLectoGo = new javax.swing.JButton();
        btnSonidoMinijuegos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPuntuacion = new javax.swing.JButton();
        btnMinijuegos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSonidoSalir.setBorder(null);
        btnSonidoSalir.setBorderPainted(false);
        btnSonidoSalir.setContentAreaFilled(false);
        btnSonidoSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSonidoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 70, 80));

        btnSonidoPuntuacion.setBorder(null);
        btnSonidoPuntuacion.setBorderPainted(false);
        btnSonidoPuntuacion.setContentAreaFilled(false);
        btnSonidoPuntuacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSonidoPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoPuntuacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSonidoPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 70, 80));

        btnGuiaLarga.setBorder(null);
        btnGuiaLarga.setBorderPainted(false);
        btnGuiaLarga.setContentAreaFilled(false);
        btnGuiaLarga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnGuiaLarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 50, 50));

        btnLectoGo.setBorder(null);
        btnLectoGo.setBorderPainted(false);
        btnLectoGo.setContentAreaFilled(false);
        btnLectoGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLectoGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 50, 50));

        btnSonidoMinijuegos.setBorder(null);
        btnSonidoMinijuegos.setBorderPainted(false);
        btnSonidoMinijuegos.setContentAreaFilled(false);
        btnSonidoMinijuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSonidoMinijuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 70, 70));

        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 290, 80));

        btnPuntuacion.setBorder(null);
        btnPuntuacion.setBorderPainted(false);
        btnPuntuacion.setContentAreaFilled(false);
        btnPuntuacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 290, 80));

        btnMinijuegos.setBorder(null);
        btnMinijuegos.setBorderPainted(false);
        btnMinijuegos.setContentAreaFilled(false);
        btnMinijuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnMinijuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 290, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuegoslectogo/assets/imagenes/Menus/MenU.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSonidoPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSonidoPuntuacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuiaLarga;
    public javax.swing.JButton btnLectoGo;
    public javax.swing.JButton btnMinijuegos;
    public javax.swing.JButton btnPuntuacion;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSonidoMinijuegos;
    public javax.swing.JButton btnSonidoPuntuacion;
    public javax.swing.JButton btnSonidoSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
