/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.CtrlVistaImagenesYPalabras;

/**
 *
 * @author Baiza
 */
public class VistaMiniImagenesYPalabra extends javax.swing.JFrame {

    
    CtrlVistaImagenesYPalabras ctrlIYP;
    
    public VistaMiniImagenesYPalabra() {
        initComponents();
        ctrlIYP = new CtrlVistaImagenesYPalabras(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPuntuacion = new javax.swing.JLabel();
        cronometroLabel = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnRepetirSonido = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnOpcionD = new javax.swing.JButton();
        btnOpcionC = new javax.swing.JButton();
        btnOpcionB = new javax.swing.JButton();
        btnOpcionA = new javax.swing.JButton();
        Imagenes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPuntuacion.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        labelPuntuacion.setForeground(new java.awt.Color(255, 51, 51));
        labelPuntuacion.setText("00");
        jPanel1.add(labelPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 120, 70));

        cronometroLabel.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        cronometroLabel.setForeground(new java.awt.Color(255, 51, 51));
        cronometroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometroLabel.setText("00");
        jPanel1.add(cronometroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 110, 60));

        btnAyuda.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAyuda.setBorder(null);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 70));

        btnRepetirSonido.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnRepetirSonido.setBorder(null);
        btnRepetirSonido.setContentAreaFilled(false);
        btnRepetirSonido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRepetirSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 60));

        btnSalir.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 190, 80));

        btnIniciar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnIniciar.setBorder(null);
        btnIniciar.setContentAreaFilled(false);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 190, 60));

        btnOpcionD.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnOpcionD.setToolTipText("");
        btnOpcionD.setBorder(null);
        btnOpcionD.setContentAreaFilled(false);
        btnOpcionD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnOpcionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 320, 80));

        btnOpcionC.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnOpcionC.setBorder(null);
        btnOpcionC.setContentAreaFilled(false);
        btnOpcionC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnOpcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 320, 80));

        btnOpcionB.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnOpcionB.setBorder(null);
        btnOpcionB.setContentAreaFilled(false);
        btnOpcionB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnOpcionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 320, 80));

        btnOpcionA.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnOpcionA.setBorder(null);
        btnOpcionA.setContentAreaFilled(false);
        btnOpcionA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnOpcionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 320, 80));
        jPanel1.add(Imagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 310, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuegoslectogo/assets/imagenes/Minijuegos/ImagenesYPalabras.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMiniImagenesYPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMiniImagenesYPalabra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Imagenes;
    public javax.swing.JButton btnAyuda;
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnOpcionA;
    public javax.swing.JButton btnOpcionB;
    public javax.swing.JButton btnOpcionC;
    public javax.swing.JButton btnOpcionD;
    public javax.swing.JButton btnRepetirSonido;
    public javax.swing.JButton btnSalir;
    public javax.swing.JLabel cronometroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelPuntuacion;
    // End of variables declaration//GEN-END:variables
}
