/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijuegoslectogo.vistas;

import javax.crypto.AEADBadTagException;
import minijuegoslectogo.controladores.CtrlVistaMiniVocales;

/**
 *
 * @author Baiza
 */
public class VistaMiniVocales extends javax.swing.JFrame {

    CtrlVistaMiniVocales ctrlVocales;
    
    /**
     * Creates new form VistaMiniVocales2
     */
    public VistaMiniVocales() {
        initComponents();
        ctrlVocales = new CtrlVistaMiniVocales(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cronometroLabel = new javax.swing.JLabel();
        labelPuntuacion = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnRepetir = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnLetraU = new javax.swing.JButton();
        btnLetraO = new javax.swing.JButton();
        btnLetraI = new javax.swing.JButton();
        btnLetraE = new javax.swing.JButton();
        btnLetraA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cronometroLabel.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        cronometroLabel.setForeground(new java.awt.Color(255, 51, 51));
        cronometroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometroLabel.setText("00");
        jPanel1.add(cronometroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 110, 60));

        labelPuntuacion.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        labelPuntuacion.setForeground(new java.awt.Color(255, 51, 51));
        labelPuntuacion.setText("00");
        jPanel1.add(labelPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 120, 80));

        btnSalir.setToolTipText("");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 220, 90));

        btnAyuda.setBorder(null);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 90, 90));

        btnRepetir.setBorder(null);
        btnRepetir.setContentAreaFilled(false);
        btnRepetir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 90));

        btnIniciar.setBorder(null);
        btnIniciar.setContentAreaFilled(false);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 280, 90));

        btnLetraU.setBorder(null);
        btnLetraU.setContentAreaFilled(false);
        btnLetraU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLetraU, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 100, 110));

        btnLetraO.setBorder(null);
        btnLetraO.setContentAreaFilled(false);
        btnLetraO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLetraO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 110, 110));

        btnLetraI.setBorder(null);
        btnLetraI.setContentAreaFilled(false);
        btnLetraI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLetraI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 100, 110));

        btnLetraE.setBorder(null);
        btnLetraE.setContentAreaFilled(false);
        btnLetraE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLetraE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 110, 110));

        btnLetraA.setBorder(null);
        btnLetraA.setContentAreaFilled(false);
        btnLetraA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLetraA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuegoslectogo/assets/imagenes/Minijuegos/vocales.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMiniVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMiniVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMiniVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMiniVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMiniVocales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAyuda;
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnLetraA;
    public javax.swing.JButton btnLetraE;
    public javax.swing.JButton btnLetraI;
    public javax.swing.JButton btnLetraO;
    public javax.swing.JButton btnLetraU;
    public javax.swing.JButton btnRepetir;
    public javax.swing.JButton btnSalir;
    public javax.swing.JLabel cronometroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelPuntuacion;
    // End of variables declaration//GEN-END:variables
}
