/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.CtrlVistaMenuMinijuegos;

/**
 *
 * @author Baiza
 */
public class VistaMenuMinijuegos extends javax.swing.JFrame {

    private CtrlVistaMenuMinijuegos objMunu;
    
    public VistaMenuMinijuegos() {
        initComponents();
        objMunu = new CtrlVistaMenuMinijuegos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sonidoSalir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnDictado = new javax.swing.JButton();
        sonidoOrdyGan = new javax.swing.JButton();
        btnOrdYGan = new javax.swing.JButton();
        sonidoAbecedario = new javax.swing.JButton();
        sonidoPalOcult = new javax.swing.JButton();
        btnPalOcult = new javax.swing.JButton();
        sonidoImaYPal = new javax.swing.JButton();
        btnImagenesYPalabras = new javax.swing.JButton();
        btnAbecedario = new javax.swing.JButton();
        sonidoLecto = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnVocales = new javax.swing.JButton();
        sonidoVocales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sonidoSalir.setBorder(null);
        sonidoSalir.setContentAreaFilled(false);
        sonidoSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 50, 60));

        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 140, 60));

        btnDictado.setBorder(null);
        btnDictado.setContentAreaFilled(false);
        btnDictado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnDictado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 180, 60));

        sonidoOrdyGan.setBorder(null);
        sonidoOrdyGan.setContentAreaFilled(false);
        sonidoOrdyGan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoOrdyGan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 50, 60));

        btnOrdYGan.setBorder(null);
        btnOrdYGan.setContentAreaFilled(false);
        btnOrdYGan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnOrdYGan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 180, 60));

        sonidoAbecedario.setBorder(null);
        sonidoAbecedario.setContentAreaFilled(false);
        sonidoAbecedario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoAbecedario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 50, 60));

        sonidoPalOcult.setBorder(null);
        sonidoPalOcult.setContentAreaFilled(false);
        sonidoPalOcult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoPalOcult, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 50, 60));

        btnPalOcult.setBorder(null);
        btnPalOcult.setContentAreaFilled(false);
        btnPalOcult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnPalOcult, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        sonidoImaYPal.setBorder(null);
        sonidoImaYPal.setContentAreaFilled(false);
        sonidoImaYPal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoImaYPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 50, 60));

        btnImagenesYPalabras.setBorder(null);
        btnImagenesYPalabras.setContentAreaFilled(false);
        btnImagenesYPalabras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnImagenesYPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 60));

        btnAbecedario.setBorder(null);
        btnAbecedario.setContentAreaFilled(false);
        btnAbecedario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAbecedario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 180, 60));

        sonidoLecto.setBorder(null);
        sonidoLecto.setContentAreaFilled(false);
        sonidoLecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoLecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 50, 60));

        btnAyuda.setBorder(null);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 60));

        btnVocales.setBorder(null);
        btnVocales.setContentAreaFilled(false);
        btnVocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, 60));

        sonidoVocales.setBorder(null);
        sonidoVocales.setContentAreaFilled(false);
        sonidoVocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(sonidoVocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuegoslectogo/assets/imagenes/Menus/MenuJuego.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuMinijuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbecedario;
    public javax.swing.JButton btnAyuda;
    public javax.swing.JButton btnDictado;
    public javax.swing.JButton btnImagenesYPalabras;
    public javax.swing.JButton btnOrdYGan;
    public javax.swing.JButton btnPalOcult;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVocales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton sonidoAbecedario;
    public javax.swing.JButton sonidoImaYPal;
    public javax.swing.JButton sonidoLecto;
    public javax.swing.JButton sonidoOrdyGan;
    public javax.swing.JButton sonidoPalOcult;
    public javax.swing.JButton sonidoSalir;
    public javax.swing.JButton sonidoVocales;
    // End of variables declaration//GEN-END:variables
}
