/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijuegoslectogo.vistas;

import minijuegoslectogo.controladores.CtrlVistaMiniAbecedario;

/**
 *
 * @author Baiza
 */
public class VistaMiniAbecedario extends javax.swing.JFrame {

    private CtrlVistaMiniAbecedario ctrlAbc;
    public VistaMiniAbecedario() {
        initComponents();
        ctrlAbc = new CtrlVistaMiniAbecedario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRepetir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnÑ = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        labelVidas = new javax.swing.JLabel();
        labelPuntuacion = new javax.swing.JLabel();
        cronometroLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRepetir.setBorder(null);
        btnRepetir.setContentAreaFilled(false);
        btnRepetir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 60, 60));

        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 60));

        btnReiniciar.setBorder(null);
        btnReiniciar.setContentAreaFilled(false);
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 200, 60));

        btnR.setBorder(null);
        btnR.setContentAreaFilled(false);
        btnR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 70, 60));

        btnS.setBorder(null);
        btnS.setContentAreaFilled(false);
        btnS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 60, 60));

        btnT.setBorder(null);
        btnT.setContentAreaFilled(false);
        btnT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 60, 60));

        btnU.setBorder(null);
        btnU.setContentAreaFilled(false);
        btnU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 70, 60));

        btnV.setBorder(null);
        btnV.setContentAreaFilled(false);
        btnV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 60, 60));

        btnW.setBorder(null);
        btnW.setContentAreaFilled(false);
        btnW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 60, 60));

        btnX.setBorder(null);
        btnX.setContentAreaFilled(false);
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 60, 60));

        btnY.setBorder(null);
        btnY.setContentAreaFilled(false);
        btnY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 60, 60));

        btnZ.setBorder(null);
        btnZ.setContentAreaFilled(false);
        btnZ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 60, 60));

        btnQ.setBorder(null);
        btnQ.setContentAreaFilled(false);
        btnQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 60));

        btnP.setBorder(null);
        btnP.setContentAreaFilled(false);
        btnP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 60, 60));

        btnO.setBorder(null);
        btnO.setContentAreaFilled(false);
        btnO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 60, 60));

        btnÑ.setBorder(null);
        btnÑ.setContentAreaFilled(false);
        btnÑ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnÑ, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 60, 60));

        btnN.setBorder(null);
        btnN.setContentAreaFilled(false);
        btnN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 60, 60));

        btnM.setBorder(null);
        btnM.setContentAreaFilled(false);
        btnM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 70, 60));

        btnL.setBorder(null);
        btnL.setContentAreaFilled(false);
        btnL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 60, 60));

        btnK.setBorder(null);
        btnK.setContentAreaFilled(false);
        btnK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 60, 60));

        btnJ.setBorder(null);
        btnJ.setContentAreaFilled(false);
        btnJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 70, 60));

        btnI.setBorder(null);
        btnI.setContentAreaFilled(false);
        btnI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 60, 60));

        btnH.setBorder(null);
        btnH.setContentAreaFilled(false);
        btnH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 60, 60));

        btnG.setBorder(null);
        btnG.setContentAreaFilled(false);
        btnG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 60, 60));

        btnF.setBorder(null);
        btnF.setContentAreaFilled(false);
        btnF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 60, 60));

        btnE.setBorder(null);
        btnE.setContentAreaFilled(false);
        btnE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 60));

        btnD.setBorder(null);
        btnD.setContentAreaFilled(false);
        btnD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 70, 60));

        btnC.setBorder(null);
        btnC.setContentAreaFilled(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 60, 60));

        btnB.setBorder(null);
        btnB.setContentAreaFilled(false);
        btnB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 60));

        btnA.setBorder(null);
        btnA.setContentAreaFilled(false);
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 60));

        labelVidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuegoslectogo/assets/imagenes/Minijuegos/tresVidas.png"))); // NOI18N
        jPanel1.add(labelVidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 200, 70));

        labelPuntuacion.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        labelPuntuacion.setForeground(new java.awt.Color(255, 51, 51));
        labelPuntuacion.setText("00");
        jPanel1.add(labelPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 130, 60));

        cronometroLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        cronometroLabel.setForeground(new java.awt.Color(255, 51, 51));
        cronometroLabel.setText("00");
        jPanel1.add(cronometroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuegoslectogo/assets/imagenes/Minijuegos/Abecedario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMiniAbecedario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMiniAbecedario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMiniAbecedario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMiniAbecedario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMiniAbecedario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnA;
    public javax.swing.JButton btnB;
    public javax.swing.JButton btnC;
    public javax.swing.JButton btnD;
    public javax.swing.JButton btnE;
    public javax.swing.JButton btnF;
    public javax.swing.JButton btnG;
    public javax.swing.JButton btnH;
    public javax.swing.JButton btnI;
    public javax.swing.JButton btnJ;
    public javax.swing.JButton btnK;
    public javax.swing.JButton btnL;
    public javax.swing.JButton btnM;
    public javax.swing.JButton btnN;
    public javax.swing.JButton btnO;
    public javax.swing.JButton btnP;
    public javax.swing.JButton btnQ;
    public javax.swing.JButton btnR;
    public javax.swing.JButton btnReiniciar;
    public javax.swing.JButton btnRepetir;
    public javax.swing.JButton btnS;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnT;
    public javax.swing.JButton btnU;
    public javax.swing.JButton btnV;
    public javax.swing.JButton btnW;
    public javax.swing.JButton btnX;
    public javax.swing.JButton btnY;
    public javax.swing.JButton btnZ;
    public javax.swing.JButton btnÑ;
    public javax.swing.JLabel cronometroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelPuntuacion;
    public javax.swing.JLabel labelVidas;
    // End of variables declaration//GEN-END:variables
}
